name: CI Pipeline for Merge Requests


on:
  pull_request:
    branches:
      - main  # Le pipeline se déclenche pour les Pull Requests vers la branche `main` (ou toute autre branche de votre choix)


jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Utilisez la version de Node.js appropriée

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # Répertoire où se trouve l'application React

      - name: Build the React app
        run: npm run build
        working-directory: ./frontend

      - name: Run linting script
        run: npm run lint  # Le script de linting est généralement défini dans `package.json`
        working-directory: ./frontend


  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'  # Utilisez la version appropriée de .NET

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend  # Répertoire où se trouve l'application .NET

      - name: Build the .NET app in Release mode
        run: dotnet build --configuration Release
        working-directory: ./backend
